version: '3.8'

services:
  drug-interaction-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - LOG_LEVEL=INFO
    volumes:
      # Mount model files as read-only
      - ./src/xgboost_model.pkl:/app/src/xgboost_model.pkl:ro
      - ./src/preprocessing_config.py:/app/src/preprocessing_config.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - drug-api-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/ssl:/etc/nginx/ssl:ro
    depends_on:
      - drug-interaction-api
    restart: unless-stopped
    networks:
      - drug-api-network
    profiles:
      - production

networks:
  drug-api-network:
    driver: bridge
